use std::fmt;

use clap::{Parser, ValueEnum};
use mlua::Lua;

/// A fresh take on neofetch
#[derive(Parser)]
#[command(version, long_about = None)]
pub struct Cli {
    /// Ascii art to show
    #[arg(value_enum, short, long)]
    pub ascii_distro: Option<AsciiDistros>,
    /// Only show logo (not implemented yet)
    #[arg(short, long, default_value_t = false)]
    pub logo_only: bool,
}

pub trait Inject {
    fn prep(&mut self) {}
    fn inject(&self, _lua: &mut Lua) {}
}

#[derive(ValueEnum, Debug, Clone, Copy, Eq, PartialEq)]
#[value(rename_all = "snake_case")]
pub enum AsciiDistros {
    Aix,
    Alpine,
    AlpineSmall,
    Alter,
    Amazon,
    Amogos,
    Anarchy,
    Android,
    AndroidSmall,
    AnimeAhegao,
    AnimeLoliSmile,
    AnimeLoliStare,
    Anime02,
    AnimeLooking,
    Antergos,
    Antix,
    AoscRetro,
    Aosc,
    Apricity,
    Arco,
    ArcoSmall,
    ArchOld,
    ArchSmall,
    Archbox,
    Archlabs,
    Archstrike,
    Arch,
    Artix,
    ArtixSmall,
    Arya,
    Bedrock,
    Bitrig,
    Blackarch,
    Blag,
    Blankon,
    Bonsai,
    Bsd,
    Bunsenlabs,
    Calculate,
    Carbs,
    Centos,
    CentosSmall,
    Chakra,
    Chaletos,
    Chapeau,
    Chrome,
    Cleanjaro,
    CleanjaroSmall,
    Clearos,
    ClearLinux,
    Clover,
    Condres,
    ContainerLinux,
    Crux,
    CruxSmall,
    Cucumber,
    Debian,
    DebianSmall,
    Deepin,
    Desaos,
    Devuan,
    Dracos,
    Dragonfly,
    DragonflySmall,
    DragonflyOld,
    Drauger,
    Elementary,
    ElementarySmall,
    Endeavouros,
    Endless,
    Eurolinux,
    Exhuerbo,
    Fedora,
    FedoraSmall,
    Feren,
    Freebsd,
    FreebsdSmall,
    Freemint,
    Frugalware,
    Funtoo,
    Galliumos,
    Garuda,
    Gentoo,
    GentooSmall,
    Gnewsense,
    Gnome,
    Gnu,
    Gobo,
    Grombyang,
    Haiku,
    HaikuSmall,
    Hash,
    Huayra,
    Hyperbola,
    HyperbolaSmall,
    Irix,
    Janus,
    Kali,
    Kaos,
    Kde,
    Kibojoe,
    Kogaion,
    Korora,
    Kslinux,
    Kubuntu,
    Lede,
    Libreelec,
    Linux,
    LinuxClassic,
    Linuxlite,
    LinuxliteSmall,
    Lubuntu,
    Lunar,
    Mac,
    MacSmall,
    MacModern,
    Mageia,
    MageiaSmall,
    Magpieos,
    Mandriva,
    Manjaro,
    ManjaroSmall,
    Maui,
    Mer,
    Minux,
    Mint,
    MintSmall,
    MintOld,
    Mx,
    MxSmall,
    Namib,
    Neptune,
    Netbsd,
    NetbsdSmall,
    Netrunner,
    Nitrux,
    Nixos,
    NixosSmall,
    Nurunner,
    Nutyx,
    Obarun,
    Obrevenge,
    Openbsd,
    OpenbsdSmall,
    Openeuler,
    Openindiana,
    Openmamba,
    Openmandriva,
    Openstage,
    OpensuseSmall,
    Opensuseleap,
    Opensusetumbleweed,
    Opensuse,
    Openwrt,
    Osmc,
    Oracle,
    Oselbrus,
    Pacbsd,
    Parabola,
    ParabolaSmall,
    Pardus,
    Parrot,
    Parsix,
    Pcbsd,
    Pclinuxos,
    Pentoo,
    Peppermint,
    Popos,
    PoposSmall,
    Porteus,
    Postmarketos,
    PostmarketosSmall,
    Proxmox,
    Puppy,
    Pureos,
    PureosSmall,
    Qubes,
    Radix,
    Raspbian,
    RaspbianSmall,
    Reborn,
    Redstar,
    Redcore,
    Redhat,
    RedhatOld,
    Refracteddevuan,
    Regata,
    Regolith,
    Rosa,
    Sabotage,
    Sabayon,
    Sailfish,
    Salentos,
    Scientific,
    Septor,
    Serene,
    Sharklinux,
    Siduction,
    Slackware,
    SlackwareSmall,
    Slitaz,
    Smartos,
    Solus,
    Sourcemage,
    Sparky,
    Star,
    Steamos,
    Solaris,
    Sunos,
    SolarisSmall,
    SunosSmall,
    Swagarch,
    Suse,
    SuseSmall,
    T2,
    Tails,
    Trisquel,
    UbuntuCinnamon,
    UbuntuBudgie,
    UbuntuGnome,
    UbuntuMate,
    UbuntuOld,
    UbuntuStudio,
    UbuntuSmall,
    Ubuntu,
    Venom,
    Void,
    VoidSmall,
    Windows10,
    Windows8,
    Windows,
    Xferience,
    Xubuntu,
    Zorin,
}

impl fmt::Display for AsciiDistros {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
